import { Html, Head, Main, NextScript } from "next/document";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Document() {
  return (
    <Html lang="en">
      <Head title={metadata.title}>
        <meta name="description" content={metadata.description} />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
